import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import rootReducer from './reducer';
import * as serviceWorker from './serviceWorker';
import { BrowserRouter as Router } from 'react-router-dom';
import {createStore,applyMiddleware} from 'redux';
import {Provider} from 'react-redux';
const store=createStore (rootReducer,applyMiddleware());
ReactDOM.render(<Provider store={store}><Router><App /></Router></Provider>, document.getElementById('root'));
serviceWorker.unregister();
