module.exports={
    mongoURI:'',
   JWT_SECRET:'',
   EMAIL_API:'',
   EMAIL_TO:'',
   JWT_RESET_PASSWORD:'',
   EMAIL_FROM:'noreply@gmail.com',
   JWT_ACCOUNT_ACTIVATION:'activate',
   JWT_COMPANY_ACTIVATION:'company',
   JWT_INTERVIEWER_ACTIVATION:'interviewer',
   ADMIN_USERNAME:'admin123',
   ADMIN_PASSWORD:'admin!@123'
}
